package:
  name: data_api
  version: 0.5.0
  
source:
  path: ../

build:
  entry_points:
    - data_api = data_api.client:cli
  
requirements:
  build:
    - python
  run:
    - python
    - requests
    - pandas
    - h5py
    - pytz
    - numpy


about:
  home: https://git.psi.ch/sf_daq/data-api_python
  license: GPLv3
